# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('knowledge_base.md', '.'),
        ('config.py', '.'),
        ('agent_manager.py', '.'),
        ('quantum_manager.py', '.'),
        ('browser_automation.py', '.'),
        ('filesystem_manager.py', '.'),
        ('opencore_manager.py', '.'),
        ('business_generator.py', '.'),
        ('ui_manager.py', '.'),
        ('state_manager.py', '.'),
        ('utils.py', '.'),
        ('models.py', '.'),
        ('logo.png', '.'),
    ],
    hiddenimports=[
        'streamlit.web.cli',
        'streamlit.runtime.scriptrunner.script_runner',
        'streamlit.runtime.state',
        'swarms',
        'langchain',
        'langchain_community',
        'langchain_openai',
        'ollama',
        'openai',
        'anthropic',
        'google.generativeai',
        'huggingface_hub',
        'transformers',
        'sentence_transformers',
        'playwright',
        'qiskit',
        'qiskit_aer',
        'pennylane',
        'cirq',
        'pillow',
        'opencv-python',
        'moviepy',
        'python-docx',
        'PyPDF2',
        'pdfminer.six',
        'python-pptx',
        'openpyxl',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'plotly',
        'requests',
        'beautifulsoup4',
        'python-dotenv',
        'tqdm',
        'pyyaml',
        'colorama',
        'rich',
        'chromadb',
        'qdrant_client',
        'faiss',
        'librosa',
        'soundfile',
        'fastapi',
        'uvicorn',
        'websockets',
        'cryptography',
        'psutil',
        'aiofiles',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Skyscope Sentinel',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='Skyscope.icns',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Skyscope Sentinel',
)

app = BUNDLE(
    coll,
    name='Skyscope Sentinel.app',
    icon='Skyscope.icns',
    bundle_identifier='com.skyscope.sentinel',
    info_plist={
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': False,
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': 'All Files',
                'CFBundleTypeRole': 'Viewer',
                'LSItemContentTypes': ['public.data'],
                'LSHandlerRank': 'Alternate'
            }
        ]
    },
)
